import React from 'react';
import { TECHNOLOGY_COLORS } from '../lib/techColors';

interface ShareCardProps {
  totalHours: number;
  currentStreak: number;
  longestStreak: number;
  topTech: { tag: string; hours: number }[];
}

const CodeIcon: React.FC = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
  </svg>
);

const StreakIcon: React.FC<{className?: string}> = ({className}) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={`h-8 w-8 ${className}`} viewBox="0 -960 960 960" fill="currentColor">
      <path d="M240-400q0 52 21 98.5t60 81.5q-1-5-1-9v-9q0-32 12-60t35-51l113-111 113 111q23 23 35 51t12 60v9q0 4-1 9 39-35 60-81.5t21-98.5q0-50-18.5-94.5T648-574q-20 13-42 19.5t-45 6.5q-62 0-107.5-41T401-690q-39 33-69 68.5t-50.5 72Q261-513 250.5-475T240-400Zm240 52-57 56q-11 11-17 25t-6 29q0 32 23.5 55t56.5 23q33 0 56.5-23t23.5-55q0-16-6-29.5T537-292l-57-56Zm0-492v132q0 34 23.5 57t57.5 23q18 0 33.5-7.5T622-658l18-22q74 42 117 117t43 163q0 134-93 227T480-80q-134 0-227-93t-93-227q0-129 86.5-245T480-840Z"/>
    </svg>
);

const LongestStreakIcon: React.FC<{className?: string}> = ({className}) => (
   <svg xmlns="http://www.w3.org/2000/svg" className={`h-8 w-8 ${className}`} viewBox="0 -960 960 960" fill="currentColor">
      <path d="m280-80 160-300-320-40 480-460h80L520-580l320 40L360-80h-80Zm222-247 161-154-269-34 63-117-160 154 268 33-63 118Zm-22-153Z"/>
   </svg>
);

const FALLBACK_COLORS = ['#f97316', '#ec4899', '#8b5cf6', '#ef4444', '#f59e0b', '#22c55e'];

const getTagColor = (tag: string, index: number): string => {
    return TECHNOLOGY_COLORS[tag] || FALLBACK_COLORS[index % FALLBACK_COLORS.length];
};

const ShareCard: React.FC<ShareCardProps> = ({ totalHours, currentStreak, longestStreak, topTech }) => {
  return (
    <div className="w-[400px] h-[580px] bg-[#030712] text-gray-200 font-sans p-8 flex flex-col justify-between" style={{
        backgroundImage: 'radial-gradient(circle at top left, #4c1d9530, transparent 50%), radial-gradient(circle at bottom right, #1e40af30, transparent 50%)'
    }}>
      <div>
        <h1 className="text-4xl font-extrabold tracking-tight text-violet-400">CodeLog</h1>
        <p className="text-lg text-gray-300">My Coding Progress</p>
        <p className="text-xs text-gray-400 mt-1">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>

      <div className="flex flex-col items-center my-6">
        <p className="text-sm text-gray-400">Total Hours Logged</p>
        <p className="text-8xl font-bold text-white tracking-tighter">{totalHours.toFixed(1)}</p>
      </div>

      <div className="grid grid-cols-2 gap-4 text-center">
        <div className="bg-black/20 rounded-xl p-4 flex flex-col items-center justify-center">
          <StreakIcon className="text-violet-400" />
          <p className="text-sm text-gray-300 mt-1">Current Streak</p>
          <p className="text-3xl font-bold text-white">{currentStreak} <span className="text-lg font-medium text-gray-400">days</span></p>
        </div>
        <div className="bg-black/20 rounded-xl p-4 flex flex-col items-center justify-center">
          <LongestStreakIcon className="text-gray-400" />
          <p className="text-sm text-gray-300 mt-1">Longest Streak</p>
          <p className="text-3xl font-bold text-white">{longestStreak} <span className="text-lg font-medium text-gray-400">days</span></p>
        </div>
      </div>
      
      {topTech.length > 0 && (
        <div className="mt-6">
            <h3 className="text-sm text-center font-medium text-gray-400 mb-2">Top Technologies</h3>
            <div className="space-y-2">
                {topTech.map((tech, index) => (
                    <div key={tech.tag} className="bg-black/20 p-2 rounded-lg flex items-center justify-between text-sm">
                        <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-sm" style={{ backgroundColor: getTagColor(tech.tag, index)}}></div>
                            <span className="font-medium text-gray-200">{tech.tag}</span>
                        </div>
                        <span className="font-mono text-gray-300">{tech.hours.toFixed(1)} hrs</span>
                    </div>
                ))}
            </div>
        </div>
      )}

      <div className="mt-auto pt-6 flex items-center justify-center text-xs text-gray-400 gap-2">
        <CodeIcon />
        <span>Generated by CodeLog</span>
      </div>
    </div>
  );
};

export default ShareCard;
